#!/bin/bash

# don't allow errors to fail silently
set -e

PREFIX="$PWD"

wget https://github.com/LLNL/Caliper/archive/refs/tags/v2.7.0.tar.gz
tar xzf v2.7.0.tar.gz
rm v2.7.0.tar.gz

cd Caliper-2.7.0
mkdir build
mkdir install
cd build
cmake -DCMAKE_INSTALL_PREFIX=${PREFIX}/Caliper-2.7.0/install ..
make
make install
cd ../..

wget https://github.com/LLNL/spotbe/archive/refs/heads/master.zip
unzip master.zip
rm master.zip
mv spotbe-master/spotdb .
rm -rf spotbe-master
